# Generated by Django 5.0.2 on 2024-02-22 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_reporter_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
